name: fitness
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  dotted_dashed_line: ^0.0.3
  fl_chart: ^0.62.0
  simple_circular_progress_bar: ^1.0.2
  simple_animation_progress_bar: ^1.6.0
  animated_toggle_switch: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/img/  

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
